<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Student extends Model {
    use HasFactory;

    protected $fillable = [
        // All: Info
        'info_name_last',
        'info_name_first',
        'info_name_suffix',
        'info_name_middle',
        'info_lrn',
        'info_sex',
        'info_birthdate',

        // SF9: Report
        'DB_SECTION_id_g7',
        'DB_SECTION_id_g8',
        'DB_SECTION_id_g9',
        'DB_SECTION_id_g10',

        'PRESERVE_DB_SECTION_name_g7',
        'PRESERVE_DB_SECTION_name_g8',
        'PRESERVE_DB_SECTION_name_g9',
        'PRESERVE_DB_SECTION_name_g10',

        'PRESERVE_DB_USER_name_last_g7',
        'PRESERVE_DB_USER_name_last_g8',
        'PRESERVE_DB_USER_name_last_g9',
        'PRESERVE_DB_USER_name_last_g10',

        'PRESERVE_DB_USER_name_first_g7',
        'PRESERVE_DB_USER_name_first_g8',
        'PRESERVE_DB_USER_name_first_g9',
        'PRESERVE_DB_USER_name_first_g10',

        'DB_YEAR_id_g7',
        'DB_YEAR_id_g8',
        'DB_YEAR_id_g9',
        'DB_YEAR_id_g10',

        'sf9_g7_report_age',
        'sf9_g7_report_transfer_input_1',
        'sf9_g7_report_transfer_input_2',
        'sf9_g7_report_transfer_input_3',
        'sf9_g7_report_transfer_input_date',

        'sf9_g8_report_age',
        'sf9_g8_report_transfer_input_1',
        'sf9_g8_report_transfer_input_2',
        'sf9_g8_report_transfer_input_3',
        'sf9_g8_report_transfer_input_date',

        'sf9_g9_report_age',
        'sf9_g9_report_transfer_input_1',
        'sf9_g9_report_transfer_input_2',
        'sf9_g9_report_transfer_input_3',
        'sf9_g9_report_transfer_input_date',

        'sf9_g10_report_age',
        'sf9_g10_report_transfer_input_1',
        'sf9_g10_report_transfer_input_2',
        'sf9_g10_report_transfer_input_3',
        'sf9_g10_report_transfer_input_date',

        // SF9: Attendance -> present
        'sf9_g7_attendance_jan_p',
        'sf9_g7_attendance_feb_p',
        'sf9_g7_attendance_mar_p',
        'sf9_g7_attendance_apr_p',
        'sf9_g7_attendance_may_p',
        'sf9_g7_attendance_jun_p',
        'sf9_g7_attendance_jul_p',
        'sf9_g7_attendance_aug_p',
        'sf9_g7_attendance_sep_p',
        'sf9_g7_attendance_oct_p',
        'sf9_g7_attendance_nov_p',
        'sf9_g7_attendance_dec_p',

        'sf9_g8_attendance_jan_p',
        'sf9_g8_attendance_feb_p',
        'sf9_g8_attendance_mar_p',
        'sf9_g8_attendance_apr_p',
        'sf9_g8_attendance_may_p',
        'sf9_g8_attendance_jun_p',
        'sf9_g8_attendance_jul_p',
        'sf9_g8_attendance_aug_p',
        'sf9_g8_attendance_sep_p',
        'sf9_g8_attendance_oct_p',
        'sf9_g8_attendance_nov_p',
        'sf9_g8_attendance_dec_p',

        'sf9_g9_attendance_jan_p',
        'sf9_g9_attendance_feb_p',
        'sf9_g9_attendance_mar_p',
        'sf9_g9_attendance_apr_p',
        'sf9_g9_attendance_may_p',
        'sf9_g9_attendance_jun_p',
        'sf9_g9_attendance_jul_p',
        'sf9_g9_attendance_aug_p',
        'sf9_g9_attendance_sep_p',
        'sf9_g9_attendance_oct_p',
        'sf9_g9_attendance_nov_p',
        'sf9_g9_attendance_dec_p',

        'sf9_g10_attendance_jan_p',
        'sf9_g10_attendance_feb_p',
        'sf9_g10_attendance_mar_p',
        'sf9_g10_attendance_apr_p',
        'sf9_g10_attendance_may_p',
        'sf9_g10_attendance_jun_p',
        'sf9_g10_attendance_jul_p',
        'sf9_g10_attendance_aug_p',
        'sf9_g10_attendance_sep_p',
        'sf9_g10_attendance_oct_p',
        'sf9_g10_attendance_nov_p',
        'sf9_g10_attendance_dec_p',

        // SF9: Attendance -> absent
        'sf9_g7_attendance_jan_a',
        'sf9_g7_attendance_feb_a',
        'sf9_g7_attendance_mar_a',
        'sf9_g7_attendance_apr_a',
        'sf9_g7_attendance_may_a',
        'sf9_g7_attendance_jun_a',
        'sf9_g7_attendance_jul_a',
        'sf9_g7_attendance_aug_a',
        'sf9_g7_attendance_sep_a',
        'sf9_g7_attendance_oct_a',
        'sf9_g7_attendance_nov_a',
        'sf9_g7_attendance_dec_a',

        'sf9_g8_attendance_jan_a',
        'sf9_g8_attendance_feb_a',
        'sf9_g8_attendance_mar_a',
        'sf9_g8_attendance_apr_a',
        'sf9_g8_attendance_may_a',
        'sf9_g8_attendance_jun_a',
        'sf9_g8_attendance_jul_a',
        'sf9_g8_attendance_aug_a',
        'sf9_g8_attendance_sep_a',
        'sf9_g8_attendance_oct_a',
        'sf9_g8_attendance_nov_a',
        'sf9_g8_attendance_dec_a',

        'sf9_g9_attendance_jan_a',
        'sf9_g9_attendance_feb_a',
        'sf9_g9_attendance_mar_a',
        'sf9_g9_attendance_apr_a',
        'sf9_g9_attendance_may_a',
        'sf9_g9_attendance_jun_a',
        'sf9_g9_attendance_jul_a',
        'sf9_g9_attendance_aug_a',
        'sf9_g9_attendance_sep_a',
        'sf9_g9_attendance_oct_a',
        'sf9_g9_attendance_nov_a',
        'sf9_g9_attendance_dec_a',

        'sf9_g10_attendance_jan_a',
        'sf9_g10_attendance_feb_a',
        'sf9_g10_attendance_mar_a',
        'sf9_g10_attendance_apr_a',
        'sf9_g10_attendance_may_a',
        'sf9_g10_attendance_jun_a',
        'sf9_g10_attendance_jul_a',
        'sf9_g10_attendance_aug_a',
        'sf9_g10_attendance_sep_a',
        'sf9_g10_attendance_oct_a',
        'sf9_g10_attendance_nov_a',
        'sf9_g10_attendance_dec_a',

        // SF9: Values -> maka - diyos
        'sf9_g7_values_qr1_md_s1',
        'sf9_g7_values_qr2_md_s1',
        'sf9_g7_values_qr3_md_s1',
        'sf9_g7_values_qr4_md_s1',
        'sf9_g7_values_qr1_md_s2',
        'sf9_g7_values_qr2_md_s2',
        'sf9_g7_values_qr3_md_s2',
        'sf9_g7_values_qr4_md_s2',

        'sf9_g8_values_qr1_md_s1',
        'sf9_g8_values_qr2_md_s1',
        'sf9_g8_values_qr3_md_s1',
        'sf9_g8_values_qr4_md_s1',
        'sf9_g8_values_qr1_md_s2',
        'sf9_g8_values_qr2_md_s2',
        'sf9_g8_values_qr3_md_s2',
        'sf9_g8_values_qr4_md_s2',

        'sf9_g9_values_qr1_md_s1',
        'sf9_g9_values_qr2_md_s1',
        'sf9_g9_values_qr3_md_s1',
        'sf9_g9_values_qr4_md_s1',
        'sf9_g9_values_qr1_md_s2',
        'sf9_g9_values_qr2_md_s2',
        'sf9_g9_values_qr3_md_s2',
        'sf9_g9_values_qr4_md_s2',

        'sf9_g10_values_qr1_md_s1',
        'sf9_g10_values_qr2_md_s1',
        'sf9_g10_values_qr3_md_s1',
        'sf9_g10_values_qr4_md_s1',
        'sf9_g10_values_qr1_md_s2',
        'sf9_g10_values_qr2_md_s2',
        'sf9_g10_values_qr3_md_s2',
        'sf9_g10_values_qr4_md_s2',

        // SF9: Values -> maka - tao
        'sf9_g7_values_qr1_mt_s1',
        'sf9_g7_values_qr2_mt_s1',
        'sf9_g7_values_qr3_mt_s1',
        'sf9_g7_values_qr4_mt_s1',
        'sf9_g7_values_qr1_mt_s2',
        'sf9_g7_values_qr2_mt_s2',
        'sf9_g7_values_qr3_mt_s2',
        'sf9_g7_values_qr4_mt_s2',

        'sf9_g8_values_qr1_mt_s1',
        'sf9_g8_values_qr2_mt_s1',
        'sf9_g8_values_qr3_mt_s1',
        'sf9_g8_values_qr4_mt_s1',
        'sf9_g8_values_qr1_mt_s2',
        'sf9_g8_values_qr2_mt_s2',
        'sf9_g8_values_qr3_mt_s2',
        'sf9_g8_values_qr4_mt_s2',

        'sf9_g9_values_qr1_mt_s1',
        'sf9_g9_values_qr2_mt_s1',
        'sf9_g9_values_qr3_mt_s1',
        'sf9_g9_values_qr4_mt_s1',
        'sf9_g9_values_qr1_mt_s2',
        'sf9_g9_values_qr2_mt_s2',
        'sf9_g9_values_qr3_mt_s2',
        'sf9_g9_values_qr4_mt_s2',

        'sf9_g10_values_qr1_mt_s1',
        'sf9_g10_values_qr2_mt_s1',
        'sf9_g10_values_qr3_mt_s1',
        'sf9_g10_values_qr4_mt_s1',
        'sf9_g10_values_qr1_mt_s2',
        'sf9_g10_values_qr2_mt_s2',
        'sf9_g10_values_qr3_mt_s2',
        'sf9_g10_values_qr4_mt_s2',

        // SF9: Values -> maka - kalikasan
        'sf9_g7_values_qr1_mk',
        'sf9_g7_values_qr2_mk',
        'sf9_g7_values_qr3_mk',
        'sf9_g7_values_qr4_mk',

        'sf9_g8_values_qr1_mk',
        'sf9_g8_values_qr2_mk',
        'sf9_g8_values_qr3_mk',
        'sf9_g8_values_qr4_mk',

        'sf9_g9_values_qr1_mk',
        'sf9_g9_values_qr2_mk',
        'sf9_g9_values_qr3_mk',
        'sf9_g9_values_qr4_mk',

        'sf9_g10_values_qr1_mk',
        'sf9_g10_values_qr2_mk',
        'sf9_g10_values_qr3_mk',
        'sf9_g10_values_qr4_mk',

        // SF9: Values -> maka - bansa
        'sf9_g7_values_qr1_mb_s1',
        'sf9_g7_values_qr2_mb_s1',
        'sf9_g7_values_qr3_mb_s1',
        'sf9_g7_values_qr4_mb_s1',
        'sf9_g7_values_qr1_mb_s2',
        'sf9_g7_values_qr2_mb_s2',
        'sf9_g7_values_qr3_mb_s2',
        'sf9_g7_values_qr4_mb_s2',

        'sf9_g8_values_qr1_mb_s1',
        'sf9_g8_values_qr2_mb_s1',
        'sf9_g8_values_qr3_mb_s1',
        'sf9_g8_values_qr4_mb_s1',
        'sf9_g8_values_qr1_mb_s2',
        'sf9_g8_values_qr2_mb_s2',
        'sf9_g8_values_qr3_mb_s2',
        'sf9_g8_values_qr4_mb_s2',

        'sf9_g9_values_qr1_mb_s1',
        'sf9_g9_values_qr2_mb_s1',
        'sf9_g9_values_qr3_mb_s1',
        'sf9_g9_values_qr4_mb_s1',
        'sf9_g9_values_qr1_mb_s2',
        'sf9_g9_values_qr2_mb_s2',
        'sf9_g9_values_qr3_mb_s2',
        'sf9_g9_values_qr4_mb_s2',

        'sf9_g10_values_qr1_mb_s1',
        'sf9_g10_values_qr2_mb_s1',
        'sf9_g10_values_qr3_mb_s1',
        'sf9_g10_values_qr4_mb_s1',
        'sf9_g10_values_qr1_mb_s2',
        'sf9_g10_values_qr2_mb_s2',
        'sf9_g10_values_qr3_mb_s2',
        'sf9_g10_values_qr4_mb_s2',

        // SF10: Enrollment
        'sf10_enrollment_elementary_boolean',
        'sf10_enrollment_elementary_average',
        'sf10_enrollment_elementary_citation',
        'sf10_enrollment_elementary_name',
        'sf10_enrollment_elementary_id',
        'sf10_enrollment_elementary_address',

        'sf10_enrollment_other_pept_boolean',
        'sf10_enrollment_other_pept_rating',
        'sf10_enrollment_other_alsae_boolean',
        'sf10_enrollment_other_alsae_rating',
        'sf10_enrollment_other_specify_boolean',
        'sf10_enrollment_other_specify_rating',
        'sf10_enrollment_other_date',
        'sf10_enrollment_other_location',

        // SF10: Scholastic record
        'sf10_g7_record_school_name',
        'sf10_g7_record_school_id',
        'sf10_g7_record_school_district',
        'sf10_g7_record_school_division',
        'sf10_g7_record_school_region',
        'sf10_g7_record_school_grade',
        'sf10_g7_record_school_section',
        'sf10_g7_record_school_year',
        'sf10_g7_record_school_teacher',
        'sf10_g7_record_remedial_date_start',
        'sf10_g7_record_remedial_date_end',

        'sf10_g8_record_school_name',
        'sf10_g8_record_school_id',
        'sf10_g8_record_school_district',
        'sf10_g8_record_school_division',
        'sf10_g8_record_school_region',
        'sf10_g8_record_school_grade',
        'sf10_g8_record_school_section',
        'sf10_g8_record_school_year',
        'sf10_g8_record_school_teacher',
        'sf10_g8_record_remedial_date_start',
        'sf10_g8_record_remedial_date_end',

        'sf10_g9_record_school_name',
        'sf10_g9_record_school_id',
        'sf10_g9_record_school_district',
        'sf10_g9_record_school_division',
        'sf10_g9_record_school_region',
        'sf10_g9_record_school_grade',
        'sf10_g9_record_school_section',
        'sf10_g9_record_school_year',
        'sf10_g9_record_school_teacher',
        'sf10_g9_record_remedial_date_start',
        'sf10_g9_record_remedial_date_end',

        'sf10_g10_record_school_name',
        'sf10_g10_record_school_id',
        'sf10_g10_record_school_district',
        'sf10_g10_record_school_division',
        'sf10_g10_record_school_region',
        'sf10_g10_record_school_grade',
        'sf10_g10_record_school_section',
        'sf10_g10_record_school_year',
        'sf10_g10_record_school_teacher',
        'sf10_g10_record_remedial_date_start',
        'sf10_g10_record_remedial_date_end',

        // All: Subject -> filipino
        'sf9_g7_subject_qr1_fil',
        'sf9_g7_subject_qr2_fil',
        'sf9_g7_subject_qr3_fil',
        'sf9_g7_subject_qr4_fil',

        'sf9_g8_subject_qr1_fil',
        'sf9_g8_subject_qr2_fil',
        'sf9_g8_subject_qr3_fil',
        'sf9_g8_subject_qr4_fil',

        'sf9_g9_subject_qr1_fil',
        'sf9_g9_subject_qr2_fil',
        'sf9_g9_subject_qr3_fil',
        'sf9_g9_subject_qr4_fil',

        'sf9_g10_subject_qr1_fil',
        'sf9_g10_subject_qr2_fil',
        'sf9_g10_subject_qr3_fil',
        'sf9_g10_subject_qr4_fil',

        'sf10_g7_subject_qr1_fil',
        'sf10_g7_subject_qr2_fil',
        'sf10_g7_subject_qr3_fil',
        'sf10_g7_subject_qr4_fil',
        'sf10_g7_subject_rem_fil',

        'sf10_g8_subject_qr1_fil',
        'sf10_g8_subject_qr2_fil',
        'sf10_g8_subject_qr3_fil',
        'sf10_g8_subject_qr4_fil',
        'sf10_g8_subject_rem_fil',

        'sf10_g9_subject_qr1_fil',
        'sf10_g9_subject_qr2_fil',
        'sf10_g9_subject_qr3_fil',
        'sf10_g9_subject_qr4_fil',
        'sf10_g9_subject_rem_fil',

        'sf10_g10_subject_qr1_fil',
        'sf10_g10_subject_qr2_fil',
        'sf10_g10_subject_qr3_fil',
        'sf10_g10_subject_qr4_fil',
        'sf10_g10_subject_rem_fil',

        // All: Subject -> english
        'sf9_g7_subject_qr1_eng',
        'sf9_g7_subject_qr2_eng',
        'sf9_g7_subject_qr3_eng',
        'sf9_g7_subject_qr4_eng',

        'sf9_g8_subject_qr1_eng',
        'sf9_g8_subject_qr2_eng',
        'sf9_g8_subject_qr3_eng',
        'sf9_g8_subject_qr4_eng',

        'sf9_g9_subject_qr1_eng',
        'sf9_g9_subject_qr2_eng',
        'sf9_g9_subject_qr3_eng',
        'sf9_g9_subject_qr4_eng',

        'sf9_g10_subject_qr1_eng',
        'sf9_g10_subject_qr2_eng',
        'sf9_g10_subject_qr3_eng',
        'sf9_g10_subject_qr4_eng',

        'sf10_g7_subject_qr1_eng',
        'sf10_g7_subject_qr2_eng',
        'sf10_g7_subject_qr3_eng',
        'sf10_g7_subject_qr4_eng',
        'sf10_g7_subject_rem_eng',

        'sf10_g8_subject_qr1_eng',
        'sf10_g8_subject_qr2_eng',
        'sf10_g8_subject_qr3_eng',
        'sf10_g8_subject_qr4_eng',
        'sf10_g8_subject_rem_eng',

        'sf10_g9_subject_qr1_eng',
        'sf10_g9_subject_qr2_eng',
        'sf10_g9_subject_qr3_eng',
        'sf10_g9_subject_qr4_eng',
        'sf10_g9_subject_rem_eng',

        'sf10_g10_subject_qr1_eng',
        'sf10_g10_subject_qr2_eng',
        'sf10_g10_subject_qr3_eng',
        'sf10_g10_subject_qr4_eng',
        'sf10_g10_subject_rem_eng',

        // All: Subject -> mathematics
        'sf9_g7_subject_qr1_mat',
        'sf9_g7_subject_qr2_mat',
        'sf9_g7_subject_qr3_mat',
        'sf9_g7_subject_qr4_mat',

        'sf9_g8_subject_qr1_mat',
        'sf9_g8_subject_qr2_mat',
        'sf9_g8_subject_qr3_mat',
        'sf9_g8_subject_qr4_mat',

        'sf9_g9_subject_qr1_mat',
        'sf9_g9_subject_qr2_mat',
        'sf9_g9_subject_qr3_mat',
        'sf9_g9_subject_qr4_mat',

        'sf9_g10_subject_qr1_mat',
        'sf9_g10_subject_qr2_mat',
        'sf9_g10_subject_qr3_mat',
        'sf9_g10_subject_qr4_mat',

        'sf10_g7_subject_qr1_mat',
        'sf10_g7_subject_qr2_mat',
        'sf10_g7_subject_qr3_mat',
        'sf10_g7_subject_qr4_mat',
        'sf10_g7_subject_rem_mat',

        'sf10_g8_subject_qr1_mat',
        'sf10_g8_subject_qr2_mat',
        'sf10_g8_subject_qr3_mat',
        'sf10_g8_subject_qr4_mat',
        'sf10_g8_subject_rem_mat',

        'sf10_g9_subject_qr1_mat',
        'sf10_g9_subject_qr2_mat',
        'sf10_g9_subject_qr3_mat',
        'sf10_g9_subject_qr4_mat',
        'sf10_g9_subject_rem_mat',

        'sf10_g10_subject_qr1_mat',
        'sf10_g10_subject_qr2_mat',
        'sf10_g10_subject_qr3_mat',
        'sf10_g10_subject_qr4_mat',
        'sf10_g10_subject_rem_mat',

        // All: Subject -> science
        'sf9_g7_subject_qr1_sci',
        'sf9_g7_subject_qr2_sci',
        'sf9_g7_subject_qr3_sci',
        'sf9_g7_subject_qr4_sci',

        'sf9_g8_subject_qr1_sci',
        'sf9_g8_subject_qr2_sci',
        'sf9_g8_subject_qr3_sci',
        'sf9_g8_subject_qr4_sci',

        'sf9_g9_subject_qr1_sci',
        'sf9_g9_subject_qr2_sci',
        'sf9_g9_subject_qr3_sci',
        'sf9_g9_subject_qr4_sci',

        'sf9_g10_subject_qr1_sci',
        'sf9_g10_subject_qr2_sci',
        'sf9_g10_subject_qr3_sci',
        'sf9_g10_subject_qr4_sci',

        'sf10_g7_subject_qr1_sci',
        'sf10_g7_subject_qr2_sci',
        'sf10_g7_subject_qr3_sci',
        'sf10_g7_subject_qr4_sci',
        'sf10_g7_subject_rem_sci',

        'sf10_g8_subject_qr1_sci',
        'sf10_g8_subject_qr2_sci',
        'sf10_g8_subject_qr3_sci',
        'sf10_g8_subject_qr4_sci',
        'sf10_g8_subject_rem_sci',

        'sf10_g9_subject_qr1_sci',
        'sf10_g9_subject_qr2_sci',
        'sf10_g9_subject_qr3_sci',
        'sf10_g9_subject_qr4_sci',
        'sf10_g9_subject_rem_sci',

        'sf10_g10_subject_qr1_sci',
        'sf10_g10_subject_qr2_sci',
        'sf10_g10_subject_qr3_sci',
        'sf10_g10_subject_qr4_sci',
        'sf10_g10_subject_rem_sci',

        // All: Subject -> araling panlipunan (ap)
        'sf9_g7_subject_qr1_ap',
        'sf9_g7_subject_qr2_ap',
        'sf9_g7_subject_qr3_ap',
        'sf9_g7_subject_qr4_ap',

        'sf9_g8_subject_qr1_ap',
        'sf9_g8_subject_qr2_ap',
        'sf9_g8_subject_qr3_ap',
        'sf9_g8_subject_qr4_ap',

        'sf9_g9_subject_qr1_ap',
        'sf9_g9_subject_qr2_ap',
        'sf9_g9_subject_qr3_ap',
        'sf9_g9_subject_qr4_ap',

        'sf9_g10_subject_qr1_ap',
        'sf9_g10_subject_qr2_ap',
        'sf9_g10_subject_qr3_ap',
        'sf9_g10_subject_qr4_ap',

        'sf10_g7_subject_qr1_ap',
        'sf10_g7_subject_qr2_ap',
        'sf10_g7_subject_qr3_ap',
        'sf10_g7_subject_qr4_ap',
        'sf10_g7_subject_rem_ap',

        'sf10_g8_subject_qr1_ap',
        'sf10_g8_subject_qr2_ap',
        'sf10_g8_subject_qr3_ap',
        'sf10_g8_subject_qr4_ap',
        'sf10_g8_subject_rem_ap',

        'sf10_g9_subject_qr1_ap',
        'sf10_g9_subject_qr2_ap',
        'sf10_g9_subject_qr3_ap',
        'sf10_g9_subject_qr4_ap',
        'sf10_g9_subject_rem_ap',

        'sf10_g10_subject_qr1_ap',
        'sf10_g10_subject_qr2_ap',
        'sf10_g10_subject_qr3_ap',
        'sf10_g10_subject_qr4_ap',
        'sf10_g10_subject_rem_ap',

        // All: Subject -> edukasyon sa pagpapakatao (ep)
        'sf9_g7_subject_qr1_ep',
        'sf9_g7_subject_qr2_ep',
        'sf9_g7_subject_qr3_ep',
        'sf9_g7_subject_qr4_ep',

        'sf9_g8_subject_qr1_ep',
        'sf9_g8_subject_qr2_ep',
        'sf9_g8_subject_qr3_ep',
        'sf9_g8_subject_qr4_ep',

        'sf9_g9_subject_qr1_ep',
        'sf9_g9_subject_qr2_ep',
        'sf9_g9_subject_qr3_ep',
        'sf9_g9_subject_qr4_ep',

        'sf9_g10_subject_qr1_ep',
        'sf9_g10_subject_qr2_ep',
        'sf9_g10_subject_qr3_ep',
        'sf9_g10_subject_qr4_ep',

        'sf10_g7_subject_qr1_ep',
        'sf10_g7_subject_qr2_ep',
        'sf10_g7_subject_qr3_ep',
        'sf10_g7_subject_qr4_ep',
        'sf10_g7_subject_rem_ep',

        'sf10_g8_subject_qr1_ep',
        'sf10_g8_subject_qr2_ep',
        'sf10_g8_subject_qr3_ep',
        'sf10_g8_subject_qr4_ep',
        'sf10_g8_subject_rem_ep',

        'sf10_g9_subject_qr1_ep',
        'sf10_g9_subject_qr2_ep',
        'sf10_g9_subject_qr3_ep',
        'sf10_g9_subject_qr4_ep',
        'sf10_g9_subject_rem_ep',

        'sf10_g10_subject_qr1_ep',
        'sf10_g10_subject_qr2_ep',
        'sf10_g10_subject_qr3_ep',
        'sf10_g10_subject_qr4_ep',
        'sf10_g10_subject_rem_ep',

        // All: Subject -> technology and livelihood education (tle)
        'sf9_g7_subject_qr1_tle',
        'sf9_g7_subject_qr2_tle',
        'sf9_g7_subject_qr3_tle',
        'sf9_g7_subject_qr4_tle',

        'sf9_g8_subject_qr1_tle',
        'sf9_g8_subject_qr2_tle',
        'sf9_g8_subject_qr3_tle',
        'sf9_g8_subject_qr4_tle',

        'sf9_g9_subject_qr1_tle',
        'sf9_g9_subject_qr2_tle',
        'sf9_g9_subject_qr3_tle',
        'sf9_g9_subject_qr4_tle',

        'sf9_g10_subject_qr1_tle',
        'sf9_g10_subject_qr2_tle',
        'sf9_g10_subject_qr3_tle',
        'sf9_g10_subject_qr4_tle',

        'sf10_g7_subject_qr1_tle',
        'sf10_g7_subject_qr2_tle',
        'sf10_g7_subject_qr3_tle',
        'sf10_g7_subject_qr4_tle',
        'sf10_g7_subject_rem_tle',

        'sf10_g8_subject_qr1_tle',
        'sf10_g8_subject_qr2_tle',
        'sf10_g8_subject_qr3_tle',
        'sf10_g8_subject_qr4_tle',
        'sf10_g8_subject_rem_tle',

        'sf10_g9_subject_qr1_tle',
        'sf10_g9_subject_qr2_tle',
        'sf10_g9_subject_qr3_tle',
        'sf10_g9_subject_qr4_tle',
        'sf10_g9_subject_rem_tle',

        'sf10_g10_subject_qr1_tle',
        'sf10_g10_subject_qr2_tle',
        'sf10_g10_subject_qr3_tle',
        'sf10_g10_subject_qr4_tle',
        'sf10_g10_subject_rem_tle',

        // All: Subject -> music
        'sf9_g7_subject_qr1_mus',
        'sf9_g7_subject_qr2_mus',
        'sf9_g7_subject_qr3_mus',
        'sf9_g7_subject_qr4_mus',

        'sf9_g8_subject_qr1_mus',
        'sf9_g8_subject_qr2_mus',
        'sf9_g8_subject_qr3_mus',
        'sf9_g8_subject_qr4_mus',

        'sf9_g9_subject_qr1_mus',
        'sf9_g9_subject_qr2_mus',
        'sf9_g9_subject_qr3_mus',
        'sf9_g9_subject_qr4_mus',

        'sf9_g10_subject_qr1_mus',
        'sf9_g10_subject_qr2_mus',
        'sf9_g10_subject_qr3_mus',
        'sf9_g10_subject_qr4_mus',

        'sf10_g7_subject_qr1_mus',
        'sf10_g7_subject_qr2_mus',
        'sf10_g7_subject_qr3_mus',
        'sf10_g7_subject_qr4_mus',
        'sf10_g7_subject_rem_mus',

        'sf10_g8_subject_qr1_mus',
        'sf10_g8_subject_qr2_mus',
        'sf10_g8_subject_qr3_mus',
        'sf10_g8_subject_qr4_mus',
        'sf10_g8_subject_rem_mus',

        'sf10_g9_subject_qr1_mus',
        'sf10_g9_subject_qr2_mus',
        'sf10_g9_subject_qr3_mus',
        'sf10_g9_subject_qr4_mus',
        'sf10_g9_subject_rem_mus',

        'sf10_g10_subject_qr1_mus',
        'sf10_g10_subject_qr2_mus',
        'sf10_g10_subject_qr3_mus',
        'sf10_g10_subject_qr4_mus',
        'sf10_g10_subject_rem_mus',

        // All: Subject -> arts
        'sf9_g7_subject_qr1_art',
        'sf9_g7_subject_qr2_art',
        'sf9_g7_subject_qr3_art',
        'sf9_g7_subject_qr4_art',

        'sf9_g8_subject_qr1_art',
        'sf9_g8_subject_qr2_art',
        'sf9_g8_subject_qr3_art',
        'sf9_g8_subject_qr4_art',

        'sf9_g9_subject_qr1_art',
        'sf9_g9_subject_qr2_art',
        'sf9_g9_subject_qr3_art',
        'sf9_g9_subject_qr4_art',

        'sf9_g10_subject_qr1_art',
        'sf9_g10_subject_qr2_art',
        'sf9_g10_subject_qr3_art',
        'sf9_g10_subject_qr4_art',

        'sf10_g7_subject_qr1_art',
        'sf10_g7_subject_qr2_art',
        'sf10_g7_subject_qr3_art',
        'sf10_g7_subject_qr4_art',
        'sf10_g7_subject_rem_art',

        'sf10_g8_subject_qr1_art',
        'sf10_g8_subject_qr2_art',
        'sf10_g8_subject_qr3_art',
        'sf10_g8_subject_qr4_art',
        'sf10_g8_subject_rem_art',

        'sf10_g9_subject_qr1_art',
        'sf10_g9_subject_qr2_art',
        'sf10_g9_subject_qr3_art',
        'sf10_g9_subject_qr4_art',
        'sf10_g9_subject_rem_art',

        'sf10_g10_subject_qr1_art',
        'sf10_g10_subject_qr2_art',
        'sf10_g10_subject_qr3_art',
        'sf10_g10_subject_qr4_art',
        'sf10_g10_subject_rem_art',

        // All: Subject -> physical education
        'sf9_g7_subject_qr1_pe',
        'sf9_g7_subject_qr2_pe',
        'sf9_g7_subject_qr3_pe',
        'sf9_g7_subject_qr4_pe',

        'sf9_g8_subject_qr1_pe',
        'sf9_g8_subject_qr2_pe',
        'sf9_g8_subject_qr3_pe',
        'sf9_g8_subject_qr4_pe',

        'sf9_g9_subject_qr1_pe',
        'sf9_g9_subject_qr2_pe',
        'sf9_g9_subject_qr3_pe',
        'sf9_g9_subject_qr4_pe',

        'sf9_g10_subject_qr1_pe',
        'sf9_g10_subject_qr2_pe',
        'sf9_g10_subject_qr3_pe',
        'sf9_g10_subject_qr4_pe',

        'sf10_g7_subject_qr1_pe',
        'sf10_g7_subject_qr2_pe',
        'sf10_g7_subject_qr3_pe',
        'sf10_g7_subject_qr4_pe',
        'sf10_g7_subject_rem_pe',

        'sf10_g8_subject_qr1_pe',
        'sf10_g8_subject_qr2_pe',
        'sf10_g8_subject_qr3_pe',
        'sf10_g8_subject_qr4_pe',
        'sf10_g8_subject_rem_pe',

        'sf10_g9_subject_qr1_pe',
        'sf10_g9_subject_qr2_pe',
        'sf10_g9_subject_qr3_pe',
        'sf10_g9_subject_qr4_pe',
        'sf10_g9_subject_rem_pe',

        'sf10_g10_subject_qr1_pe',
        'sf10_g10_subject_qr2_pe',
        'sf10_g10_subject_qr3_pe',
        'sf10_g10_subject_qr4_pe',
        'sf10_g10_subject_rem_pe',

        // All: Subject -> health
        'sf9_g7_subject_qr1_hp',
        'sf9_g7_subject_qr2_hp',
        'sf9_g7_subject_qr3_hp',
        'sf9_g7_subject_qr4_hp',

        'sf9_g8_subject_qr1_hp',
        'sf9_g8_subject_qr2_hp',
        'sf9_g8_subject_qr3_hp',
        'sf9_g8_subject_qr4_hp',

        'sf9_g9_subject_qr1_hp',
        'sf9_g9_subject_qr2_hp',
        'sf9_g9_subject_qr3_hp',
        'sf9_g9_subject_qr4_hp',

        'sf9_g10_subject_qr1_hp',
        'sf9_g10_subject_qr2_hp',
        'sf9_g10_subject_qr3_hp',
        'sf9_g10_subject_qr4_hp',

        'sf10_g7_subject_qr1_hp',
        'sf10_g7_subject_qr2_hp',
        'sf10_g7_subject_qr3_hp',
        'sf10_g7_subject_qr4_hp',
        'sf10_g7_subject_rem_hp',

        'sf10_g8_subject_qr1_hp',
        'sf10_g8_subject_qr2_hp',
        'sf10_g8_subject_qr3_hp',
        'sf10_g8_subject_qr4_hp',
        'sf10_g8_subject_rem_hp',

        'sf10_g9_subject_qr1_hp',
        'sf10_g9_subject_qr2_hp',
        'sf10_g9_subject_qr3_hp',
        'sf10_g9_subject_qr4_hp',
        'sf10_g9_subject_rem_hp',

        'sf10_g10_subject_qr1_hp',
        'sf10_g10_subject_qr2_hp',
        'sf10_g10_subject_qr3_hp',
        'sf10_g10_subject_qr4_hp',
        'sf10_g10_subject_rem_hp',

        // NOTE: Place special subject here
    ];
}