<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Student extends Model {
    use HasFactory;
    
    public $timestamps = false;

    protected $guarded = [];

    protected $fillable = [
        // COMPLETE: 03 | ALL -> scholastic record -> subject -> filipino
        'ALL_g7_subject_fil_qr1',
        'ALL_g7_subject_fil_qr2',
        'ALL_g7_subject_fil_qr3',
        'ALL_g7_subject_fil_qr4',
        'ALL_g7_subject_fil_rem_fr',
        'ALL_g7_subject_fil_rem_cm',
        'ALL_g7_subject_fil_rem_rf',

        'ALL_g8_subject_fil_qr1',
        'ALL_g8_subject_fil_qr2',
        'ALL_g8_subject_fil_qr3',
        'ALL_g8_subject_fil_qr4',
        'ALL_g8_subject_fil_rem_fr',
        'ALL_g8_subject_fil_rem_cm',
        'ALL_g8_subject_fil_rem_rf',

        'ALL_g9_subject_fil_qr1',
        'ALL_g9_subject_fil_qr2',
        'ALL_g9_subject_fil_qr3',
        'ALL_g9_subject_fil_qr4',
        'ALL_g9_subject_fil_rem_fr',
        'ALL_g9_subject_fil_rem_cm',
        'ALL_g9_subject_fil_rem_rf',

        'ALL_g10_subject_fil_qr1',
        'ALL_g10_subject_fil_qr2',
        'ALL_g10_subject_fil_qr3',
        'ALL_g10_subject_fil_qr4',
        'ALL_g10_subject_fil_rem_fr',
        'ALL_g10_subject_fil_rem_cm',
        'ALL_g10_subject_fil_rem_rf',

        // COMPLETE: 04 | ALL -> scholastic record -> subject -> english
        'ALL_g7_subject_eng_qr1',
        'ALL_g7_subject_eng_qr2',
        'ALL_g7_subject_eng_qr3',
        'ALL_g7_subject_eng_qr4',
        'ALL_g7_subject_eng_rem_fr',
        'ALL_g7_subject_eng_rem_cm',
        'ALL_g7_subject_eng_rem_rf',

        'ALL_g8_subject_eng_qr1',
        'ALL_g8_subject_eng_qr2',
        'ALL_g8_subject_eng_qr3',
        'ALL_g8_subject_eng_qr4',
        'ALL_g8_subject_eng_rem_fr',
        'ALL_g8_subject_eng_rem_cm',
        'ALL_g8_subject_eng_rem_rf',

        'ALL_g9_subject_eng_qr1',
        'ALL_g9_subject_eng_qr2',
        'ALL_g9_subject_eng_qr3',
        'ALL_g9_subject_eng_qr4',
        'ALL_g9_subject_eng_rem_fr',
        'ALL_g9_subject_eng_rem_cm',
        'ALL_g9_subject_eng_rem_rf',

        'ALL_g10_subject_eng_qr1',
        'ALL_g10_subject_eng_qr2',
        'ALL_g10_subject_eng_qr3',
        'ALL_g10_subject_eng_qr4',
        'ALL_g10_subject_eng_rem_fr',
        'ALL_g10_subject_eng_rem_cm',
        'ALL_g10_subject_eng_rem_rf',

        // COMPLETE: 05 | ALL -> scholastic record -> subject -> mathematics
        'ALL_g7_subject_mat_qr1',
        'ALL_g7_subject_mat_qr2',
        'ALL_g7_subject_mat_qr3',
        'ALL_g7_subject_mat_qr4',
        'ALL_g7_subject_mat_rem_fr',
        'ALL_g7_subject_mat_rem_cm',
        'ALL_g7_subject_mat_rem_rf',

        'ALL_g8_subject_mat_qr1',
        'ALL_g8_subject_mat_qr2',
        'ALL_g8_subject_mat_qr3',
        'ALL_g8_subject_mat_qr4',
        'ALL_g8_subject_mat_rem_fr',
        'ALL_g8_subject_mat_rem_cm',
        'ALL_g8_subject_mat_rem_rf',

        'ALL_g9_subject_mat_qr1',
        'ALL_g9_subject_mat_qr2',
        'ALL_g9_subject_mat_qr3',
        'ALL_g9_subject_mat_qr4',
        'ALL_g9_subject_mat_rem_fr',
        'ALL_g9_subject_mat_rem_cm',
        'ALL_g9_subject_mat_rem_rf',

        'ALL_g10_subject_mat_qr1',
        'ALL_g10_subject_mat_qr2',
        'ALL_g10_subject_mat_qr3',
        'ALL_g10_subject_mat_qr4',
        'ALL_g10_subject_mat_rem_fr',
        'ALL_g10_subject_mat_rem_cm',
        'ALL_g10_subject_mat_rem_rf',

        // COMPLETE: 06 | ALL -> scholastic record -> subject -> science
        'ALL_g7_subject_sci_qr1',
        'ALL_g7_subject_sci_qr2',
        'ALL_g7_subject_sci_qr3',
        'ALL_g7_subject_sci_qr4',
        'ALL_g7_subject_sci_rem_fr',
        'ALL_g7_subject_sci_rem_cm',
        'ALL_g7_subject_sci_rem_rf',

        'ALL_g8_subject_sci_qr1',
        'ALL_g8_subject_sci_qr2',
        'ALL_g8_subject_sci_qr3',
        'ALL_g8_subject_sci_qr4',
        'ALL_g8_subject_sci_rem_fr',
        'ALL_g8_subject_sci_rem_cm',
        'ALL_g8_subject_sci_rem_rf',
        
        'ALL_g9_subject_sci_qr1',
        'ALL_g9_subject_sci_qr2',
        'ALL_g9_subject_sci_qr3',
        'ALL_g9_subject_sci_qr4',
        'ALL_g9_subject_sci_rem_fr',
        'ALL_g9_subject_sci_rem_cm',
        'ALL_g9_subject_sci_rem_rf',
        
        'ALL_g10_subject_sci_qr1',
        'ALL_g10_subject_sci_qr2',
        'ALL_g10_subject_sci_qr3',
        'ALL_g10_subject_sci_qr4',
        'ALL_g10_subject_sci_rem_fr',
        'ALL_g10_subject_sci_rem_cm',
        'ALL_g10_subject_sci_rem_rf',

        // COMPLETE: 07 | ALL -> scholastic record -> subject -> araling panlipunan (ap)
        'ALL_g7_subject_ap_qr1',
        'ALL_g7_subject_ap_qr2',
        'ALL_g7_subject_ap_qr3',
        'ALL_g7_subject_ap_qr4',
        'ALL_g7_subject_ap_rem_fr',
        'ALL_g7_subject_ap_rem_cm',
        'ALL_g7_subject_ap_rem_rf',
        
        'ALL_g8_subject_ap_qr1',
        'ALL_g8_subject_ap_qr2',
        'ALL_g8_subject_ap_qr3',
        'ALL_g8_subject_ap_qr4',
        'ALL_g8_subject_ap_rem_fr',
        'ALL_g8_subject_ap_rem_cm',
        'ALL_g8_subject_ap_rem_rf',
        
        'ALL_g9_subject_ap_qr1',
        'ALL_g9_subject_ap_qr2',
        'ALL_g9_subject_ap_qr3',
        'ALL_g9_subject_ap_qr4',
        'ALL_g9_subject_ap_rem_fr',
        'ALL_g9_subject_ap_rem_cm',
        'ALL_g9_subject_ap_rem_rf',
        
        'ALL_g10_subject_ap_qr1',
        'ALL_g10_subject_ap_qr2',
        'ALL_g10_subject_ap_qr3',
        'ALL_g10_subject_ap_qr4',
        'ALL_g10_subject_ap_rem_fr',
        'ALL_g10_subject_ap_rem_cm',
        'ALL_g10_subject_ap_rem_rf',

        // COMPLETE: 08 | ALL -> scholastic record -> subject -> edukasyon sa pagpapakatao (ep)
        'ALL_g7_subject_ep_qr1',
        'ALL_g7_subject_ep_qr2',
        'ALL_g7_subject_ep_qr3',
        'ALL_g7_subject_ep_qr4',
        'ALL_g7_subject_ep_rem_fr',
        'ALL_g7_subject_ep_rem_cm',
        'ALL_g7_subject_ep_rem_rf',

        'ALL_g8_subject_ep_qr1',
        'ALL_g8_subject_ep_qr2',
        'ALL_g8_subject_ep_qr3',
        'ALL_g8_subject_ep_qr4',
        'ALL_g8_subject_ep_rem_fr',
        'ALL_g8_subject_ep_rem_cm',
        'ALL_g8_subject_ep_rem_rf',

        'ALL_g9_subject_ep_qr1',
        'ALL_g9_subject_ep_qr2',
        'ALL_g9_subject_ep_qr3',
        'ALL_g9_subject_ep_qr4',
        'ALL_g9_subject_ep_rem_fr',
        'ALL_g9_subject_ep_rem_cm',
        'ALL_g9_subject_ep_rem_rf',

        'ALL_g10_subject_ep_qr1',
        'ALL_g10_subject_ep_qr2',
        'ALL_g10_subject_ep_qr3',
        'ALL_g10_subject_ep_qr4',
        'ALL_g10_subject_ep_rem_fr',
        'ALL_g10_subject_ep_rem_cm',
        'ALL_g10_subject_ep_rem_rf',

        // COMPLETE: 09 | ALL -> scholastic record -> subject -> technology and livelihood education (tle)
        'ALL_g7_subject_tle_qr1',
        'ALL_g7_subject_tle_qr2',
        'ALL_g7_subject_tle_qr3',
        'ALL_g7_subject_tle_qr4',
        'ALL_g7_subject_tle_rem_fr',
        'ALL_g7_subject_tle_rem_cm',
        'ALL_g7_subject_tle_rem_rf',

        'ALL_g8_subject_tle_qr1',
        'ALL_g8_subject_tle_qr2',
        'ALL_g8_subject_tle_qr3',
        'ALL_g8_subject_tle_qr4',
        'ALL_g8_subject_tle_rem_fr',
        'ALL_g8_subject_tle_rem_cm',
        'ALL_g8_subject_tle_rem_rf',

        'ALL_g9_subject_tle_qr1',
        'ALL_g9_subject_tle_qr2',
        'ALL_g9_subject_tle_qr3',
        'ALL_g9_subject_tle_qr4',
        'ALL_g9_subject_tle_rem_fr',
        'ALL_g9_subject_tle_rem_cm',
        'ALL_g9_subject_tle_rem_rf',

        'ALL_g10_subject_tle_qr1',
        'ALL_g10_subject_tle_qr2',
        'ALL_g10_subject_tle_qr3',
        'ALL_g10_subject_tle_qr4',
        'ALL_g10_subject_tle_rem_fr',
        'ALL_g10_subject_tle_rem_cm',
        'ALL_g10_subject_tle_rem_rf',

        // COMPLETE: 10 | ALL -> scholastic record -> subject -> music
        'ALL_g7_subject_mus_qr1',
        'ALL_g7_subject_mus_qr2',
        'ALL_g7_subject_mus_qr3',
        'ALL_g7_subject_mus_qr4',
        'ALL_g7_subject_mus_rem_fr',
        'ALL_g7_subject_mus_rem_cm',
        'ALL_g7_subject_mus_rem_rf',

        'ALL_g8_subject_mus_qr1',
        'ALL_g8_subject_mus_qr2',
        'ALL_g8_subject_mus_qr3',
        'ALL_g8_subject_mus_qr4',
        'ALL_g8_subject_mus_rem_fr',
        'ALL_g8_subject_mus_rem_cm',
        'ALL_g8_subject_mus_rem_rf',

        'ALL_g9_subject_mus_qr1',
        'ALL_g9_subject_mus_qr2',
        'ALL_g9_subject_mus_qr3',
        'ALL_g9_subject_mus_qr4',
        'ALL_g9_subject_mus_rem_fr',
        'ALL_g9_subject_mus_rem_cm',
        'ALL_g9_subject_mus_rem_rf',

        'ALL_g10_subject_mus_qr1',
        'ALL_g10_subject_mus_qr2',
        'ALL_g10_subject_mus_qr3',
        'ALL_g10_subject_mus_qr4',
        'ALL_g10_subject_mus_rem_fr',
        'ALL_g10_subject_mus_rem_cm',
        'ALL_g10_subject_mus_rem_rf',

        // COMPLETE: 11 | ALL -> scholastic record -> subject -> arts
        'ALL_g7_subject_art_qr1',
        'ALL_g7_subject_art_qr2',
        'ALL_g7_subject_art_qr3',
        'ALL_g7_subject_art_qr4',
        'ALL_g7_subject_art_rem_fr',
        'ALL_g7_subject_art_rem_cm',
        'ALL_g7_subject_art_rem_rf',

        'ALL_g8_subject_art_qr1',
        'ALL_g8_subject_art_qr2',
        'ALL_g8_subject_art_qr3',
        'ALL_g8_subject_art_qr4',
        'ALL_g8_subject_art_rem_fr',
        'ALL_g8_subject_art_rem_cm',
        'ALL_g8_subject_art_rem_rf',

        'ALL_g9_subject_art_qr1',
        'ALL_g9_subject_art_qr2',
        'ALL_g9_subject_art_qr3',
        'ALL_g9_subject_art_qr4',
        'ALL_g9_subject_art_rem_fr',
        'ALL_g9_subject_art_rem_cm',
        'ALL_g9_subject_art_rem_rf',

        'ALL_g10_subject_art_qr1',
        'ALL_g10_subject_art_qr2',
        'ALL_g10_subject_art_qr3',
        'ALL_g10_subject_art_qr4',
        'ALL_g10_subject_art_rem_fr',
        'ALL_g10_subject_art_rem_cm',
        'ALL_g10_subject_art_rem_rf',

        // COMPLETE: 12 | ALL -> scholastic record -> subject -> physical education
        'ALL_g7_subject_pe_qr1',
        'ALL_g7_subject_pe_qr2',
        'ALL_g7_subject_pe_qr3',
        'ALL_g7_subject_pe_qr4',
        'ALL_g7_subject_pe_rem_fr',
        'ALL_g7_subject_pe_rem_cm',
        'ALL_g7_subject_pe_rem_rf',

        'ALL_g8_subject_pe_qr1',
        'ALL_g8_subject_pe_qr2',
        'ALL_g8_subject_pe_qr3',
        'ALL_g8_subject_pe_qr4',
        'ALL_g8_subject_pe_rem_fr',
        'ALL_g8_subject_pe_rem_cm',
        'ALL_g8_subject_pe_rem_rf',

        'ALL_g9_subject_pe_qr1',
        'ALL_g9_subject_pe_qr2',
        'ALL_g9_subject_pe_qr3',
        'ALL_g9_subject_pe_qr4',
        'ALL_g9_subject_pe_rem_fr',
        'ALL_g9_subject_pe_rem_cm',
        'ALL_g9_subject_pe_rem_rf',

        'ALL_g10_subject_pe_qr1',
        'ALL_g10_subject_pe_qr2',
        'ALL_g10_subject_pe_qr3',
        'ALL_g10_subject_pe_qr4',
        'ALL_g10_subject_pe_rem_fr',
        'ALL_g10_subject_pe_rem_cm',
        'ALL_g10_subject_pe_rem_rf',

        // COMPLETE: 13 | ALL -> scholastic record -> subject -> health
        'ALL_g7_subject_hp_qr1',
        'ALL_g7_subject_hp_qr2',
        'ALL_g7_subject_hp_qr3',
        'ALL_g7_subject_hp_qr4',
        'ALL_g7_subject_hp_rem_fr',
        'ALL_g7_subject_hp_rem_cm',
        'ALL_g7_subject_hp_rem_rf',

        'ALL_g8_subject_hp_qr1',
        'ALL_g8_subject_hp_qr2',
        'ALL_g8_subject_hp_qr3',
        'ALL_g8_subject_hp_qr4',
        'ALL_g8_subject_hp_rem_fr',
        'ALL_g8_subject_hp_rem_cm',
        'ALL_g8_subject_hp_rem_rf',

        'ALL_g9_subject_hp_qr1',
        'ALL_g9_subject_hp_qr2',
        'ALL_g9_subject_hp_qr3',
        'ALL_g9_subject_hp_qr4',
        'ALL_g9_subject_hp_rem_fr',
        'ALL_g9_subject_hp_rem_cm',
        'ALL_g9_subject_hp_rem_rf',

        'ALL_g10_subject_hp_qr1',
        'ALL_g10_subject_hp_qr2',
        'ALL_g10_subject_hp_qr3',
        'ALL_g10_subject_hp_qr4',
        'ALL_g10_subject_hp_rem_fr',
        'ALL_g10_subject_hp_rem_cm',
        'ALL_g10_subject_hp_rem_rf',

        // COMPLETE: 14 | SF9 -> attendance -> days present
        'SF9_g7_attendance_p_jan',
        'SF9_g7_attendance_p_feb',
        'SF9_g7_attendance_p_mar',
        'SF9_g7_attendance_p_apr',
        'SF9_g7_attendance_p_may',
        'SF9_g7_attendance_p_jun',
        'SF9_g7_attendance_p_jul',
        'SF9_g7_attendance_p_aug',
        'SF9_g7_attendance_p_sep',
        'SF9_g7_attendance_p_oct',
        'SF9_g7_attendance_p_nov',
        'SF9_g7_attendance_p_dec',
        
        'SF9_g8_attendance_p_jan',
        'SF9_g8_attendance_p_feb',
        'SF9_g8_attendance_p_mar',
        'SF9_g8_attendance_p_apr',
        'SF9_g8_attendance_p_may',
        'SF9_g8_attendance_p_jun',
        'SF9_g8_attendance_p_jul',
        'SF9_g8_attendance_p_aug',
        'SF9_g8_attendance_p_sep',
        'SF9_g8_attendance_p_oct',
        'SF9_g8_attendance_p_nov',
        'SF9_g8_attendance_p_dec',
        
        'SF9_g9_attendance_p_jan',
        'SF9_g9_attendance_p_feb',
        'SF9_g9_attendance_p_mar',
        'SF9_g9_attendance_p_apr',
        'SF9_g9_attendance_p_may',
        'SF9_g9_attendance_p_jun',
        'SF9_g9_attendance_p_jul',
        'SF9_g9_attendance_p_aug',
        'SF9_g9_attendance_p_sep',
        'SF9_g9_attendance_p_oct',
        'SF9_g9_attendance_p_nov',
        'SF9_g9_attendance_p_dec',
        
        'SF9_g10_attendance_p_jan',
        'SF9_g10_attendance_p_feb',
        'SF9_g10_attendance_p_mar',
        'SF9_g10_attendance_p_apr',
        'SF9_g10_attendance_p_may',
        'SF9_g10_attendance_p_jun',
        'SF9_g10_attendance_p_jul',
        'SF9_g10_attendance_p_aug',
        'SF9_g10_attendance_p_sep',
        'SF9_g10_attendance_p_oct',
        'SF9_g10_attendance_p_nov',
        'SF9_g10_attendance_p_dec',

        // COMPLETE: 15 | SF9 -> attendance -> days absent
        'SF9_g7_attendance_a_jan',
        'SF9_g7_attendance_a_feb',
        'SF9_g7_attendance_a_mar',
        'SF9_g7_attendance_a_apr',
        'SF9_g7_attendance_a_may',
        'SF9_g7_attendance_a_jun',
        'SF9_g7_attendance_a_jul',
        'SF9_g7_attendance_a_aug',
        'SF9_g7_attendance_a_sep',
        'SF9_g7_attendance_a_oct',
        'SF9_g7_attendance_a_nov',
        'SF9_g7_attendance_a_dec',
        
        'SF9_g8_attendance_a_jan',
        'SF9_g8_attendance_a_feb',
        'SF9_g8_attendance_a_mar',
        'SF9_g8_attendance_a_apr',
        'SF9_g8_attendance_a_may',
        'SF9_g8_attendance_a_jun',
        'SF9_g8_attendance_a_jul',
        'SF9_g8_attendance_a_aug',
        'SF9_g8_attendance_a_sep',
        'SF9_g8_attendance_a_oct',
        'SF9_g8_attendance_a_nov',
        'SF9_g8_attendance_a_dec',
        
        'SF9_g9_attendance_a_jan',
        'SF9_g9_attendance_a_feb',
        'SF9_g9_attendance_a_mar',
        'SF9_g9_attendance_a_apr',
        'SF9_g9_attendance_a_may',
        'SF9_g9_attendance_a_jun',
        'SF9_g9_attendance_a_jul',
        'SF9_g9_attendance_a_aug',
        'SF9_g9_attendance_a_sep',
        'SF9_g9_attendance_a_oct',
        'SF9_g9_attendance_a_nov',
        'SF9_g9_attendance_a_dec',
        
        'SF9_g10_attendance_a_jan',
        'SF9_g10_attendance_a_feb',
        'SF9_g10_attendance_a_mar',
        'SF9_g10_attendance_a_apr',
        'SF9_g10_attendance_a_may',
        'SF9_g10_attendance_a_jun',
        'SF9_g10_attendance_a_jul',
        'SF9_g10_attendance_a_aug',
        'SF9_g10_attendance_a_sep',
        'SF9_g10_attendance_a_oct',
        'SF9_g10_attendance_a_nov',
        'SF9_g10_attendance_a_dec',

        // COMPLETE: 16 | SF9 -> observed values -> maka - diyos
        'SF9_g7_values_md_s1_qr1',
        'SF9_g7_values_md_s1_qr2',
        'SF9_g7_values_md_s1_qr3',
        'SF9_g7_values_md_s1_qr4',
        'SF9_g7_values_md_s2_qr1',
        'SF9_g7_values_md_s2_qr2',
        'SF9_g7_values_md_s2_qr3',
        'SF9_g7_values_md_s2_qr4',

        'SF9_g8_values_md_s1_qr1',
        'SF9_g8_values_md_s1_qr2',
        'SF9_g8_values_md_s1_qr3',
        'SF9_g8_values_md_s1_qr4',
        'SF9_g8_values_md_s2_qr1',
        'SF9_g8_values_md_s2_qr2',
        'SF9_g8_values_md_s2_qr3',
        'SF9_g8_values_md_s2_qr4',

        'SF9_g9_values_md_s1_qr1',
        'SF9_g9_values_md_s1_qr2',
        'SF9_g9_values_md_s1_qr3',
        'SF9_g9_values_md_s1_qr4',
        'SF9_g9_values_md_s2_qr1',
        'SF9_g9_values_md_s2_qr2',
        'SF9_g9_values_md_s2_qr3',
        'SF9_g9_values_md_s2_qr4',

        'SF9_g10_values_md_s1_qr1',
        'SF9_g10_values_md_s1_qr2',
        'SF9_g10_values_md_s1_qr3',
        'SF9_g10_values_md_s1_qr4',
        'SF9_g10_values_md_s2_qr1',
        'SF9_g10_values_md_s2_qr2',
        'SF9_g10_values_md_s2_qr3',
        'SF9_g10_values_md_s2_qr4',

        // COMPLETE: 17 | SF9 -> observed values -> maka - tao
        'SF9_g7_values_mt_s1_qr1',
        'SF9_g7_values_mt_s1_qr2',
        'SF9_g7_values_mt_s1_qr3',
        'SF9_g7_values_mt_s1_qr4',
        'SF9_g7_values_mt_s2_qr1',
        'SF9_g7_values_mt_s2_qr2',
        'SF9_g7_values_mt_s2_qr3',
        'SF9_g7_values_mt_s2_qr4',

        'SF9_g8_values_mt_s1_qr1',
        'SF9_g8_values_mt_s1_qr2',
        'SF9_g8_values_mt_s1_qr3',
        'SF9_g8_values_mt_s1_qr4',
        'SF9_g8_values_mt_s2_qr1',
        'SF9_g8_values_mt_s2_qr2',
        'SF9_g8_values_mt_s2_qr3',
        'SF9_g8_values_mt_s2_qr4',

        'SF9_g9_values_mt_s1_qr1',
        'SF9_g9_values_mt_s1_qr2',
        'SF9_g9_values_mt_s1_qr3',
        'SF9_g9_values_mt_s1_qr4',
        'SF9_g9_values_mt_s2_qr1',
        'SF9_g9_values_mt_s2_qr2',
        'SF9_g9_values_mt_s2_qr3',
        'SF9_g9_values_mt_s2_qr4',

        'SF9_g10_values_mt_s1_qr1',
        'SF9_g10_values_mt_s1_qr2',
        'SF9_g10_values_mt_s1_qr3',
        'SF9_g10_values_mt_s1_qr4',
        'SF9_g10_values_mt_s2_qr1',
        'SF9_g10_values_mt_s2_qr2',
        'SF9_g10_values_mt_s2_qr3',
        'SF9_g10_values_mt_s2_qr4',

        // COMPLETE: 18 | SF9 -> observed values -> maka - kalikasan
        'SF9_g7_values_mk_qr1',
        'SF9_g7_values_mk_qr2',
        'SF9_g7_values_mk_qr3',
        'SF9_g7_values_mk_qr4',

        'SF9_g8_values_mk_qr1',
        'SF9_g8_values_mk_qr2',
        'SF9_g8_values_mk_qr3',
        'SF9_g8_values_mk_qr4',

        'SF9_g9_values_mk_qr1',
        'SF9_g9_values_mk_qr2',
        'SF9_g9_values_mk_qr3',
        'SF9_g9_values_mk_qr4',

        'SF9_g10_values_mk_qr1',
        'SF9_g10_values_mk_qr2',
        'SF9_g10_values_mk_qr3',
        'SF9_g10_values_mk_qr4',

        // COMPLETE: 19 | SF9 -> observed values -> maka - bansa
        'SF9_g7_values_mb_s1_qr1',
        'SF9_g7_values_mb_s1_qr2',
        'SF9_g7_values_mb_s1_qr3',
        'SF9_g7_values_mb_s1_qr4',
        'SF9_g7_values_mb_s2_qr1',
        'SF9_g7_values_mb_s2_qr2',
        'SF9_g7_values_mb_s2_qr3',
        'SF9_g7_values_mb_s2_qr4',

        'SF9_g8_values_mb_s1_qr1',
        'SF9_g8_values_mb_s1_qr2',
        'SF9_g8_values_mb_s1_qr3',
        'SF9_g8_values_mb_s1_qr4',
        'SF9_g8_values_mb_s2_qr1',
        'SF9_g8_values_mb_s2_qr2',
        'SF9_g8_values_mb_s2_qr3',
        'SF9_g8_values_mb_s2_qr4',

        'SF9_g9_values_mb_s1_qr1',
        'SF9_g9_values_mb_s1_qr2',
        'SF9_g9_values_mb_s1_qr3',
        'SF9_g9_values_mb_s1_qr4',
        'SF9_g9_values_mb_s2_qr1',
        'SF9_g9_values_mb_s2_qr2',
        'SF9_g9_values_mb_s2_qr3',
        'SF9_g9_values_mb_s2_qr4',

        'SF9_g10_values_mb_s1_qr1',
        'SF9_g10_values_mb_s1_qr2',
        'SF9_g10_values_mb_s1_qr3',
        'SF9_g10_values_mb_s1_qr4',
        'SF9_g10_values_mb_s2_qr1',
        'SF9_g10_values_mb_s2_qr2',
        'SF9_g10_values_mb_s2_qr3',
        'SF9_g10_values_mb_s2_qr4',
    ];
}
